const PH={
  business:'Pet Haven Mobile Grooming',
  phone:'+2348084109364',
  phoneDisplay:'+234 808 410 9364',
  services:[
    {id:'full-groom',name:'Full Grooming Session'},
    {id:'bath-blowdry',name:'Bath & Blow-Dry'},
    {id:'nail-care',name:'Nail Care'},
    {id:'coat-care',name:'Coat Care & De-shedding'},
    {id:'puppy-groom',name:'Puppy Intro Groom'},
    {id:'mobile-grooming',name:'Mobile Home Grooming'}
  ]
};
function getBookings(){try{return JSON.parse(localStorage.getItem('petHavenBookings')||'[]')}catch{return[]}}
function saveBookings(rows){localStorage.setItem('petHavenBookings',JSON.stringify(rows))}
function uid(prefix='PH'){return prefix+'-'+Date.now().toString(36).toUpperCase()+'-'+Math.random().toString(36).slice(2,6).toUpperCase()}
function setupNav(){const b=document.querySelector('.menu-btn'),m=document.querySelector('.mobile-nav');if(b&&m)b.addEventListener('click',()=>{m.classList.toggle('open');b.setAttribute('aria-expanded',m.classList.contains('open'))})}
function setupBooking(){const f=document.getElementById('bookingForm');if(!f)return;const params=new URLSearchParams(location.search);if(params.get('service')){const s=f.querySelector('[name="service"]');if(s)s.value=params.get('service')}
 const date=f.querySelector('[name="date"]');if(date){const tomorrow=new Date(Date.now()+86400000);date.min=tomorrow.toISOString().slice(0,10)}
 f.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(f);const booking={id:uid(),createdAt:new Date().toISOString(),status:'New',customerName:fd.get('customerName'),phone:fd.get('phone'),email:fd.get('email'),petName:fd.get('petName'),petType:fd.get('petType'),breed:fd.get('breed'),petSize:fd.get('petSize'),service:fd.get('service'),date:fd.get('date'),time:fd.get('time'),area:fd.get('area'),address:fd.get('address'),notes:fd.get('notes')};const rows=getBookings();rows.unshift(booking);saveBookings(rows);localStorage.setItem('petHavenLastBooking',JSON.stringify(booking));location.href='booking-success.html'})}
function setupSuccess(){const el=document.getElementById('bookingSummary');if(!el)return;let b;try{b=JSON.parse(localStorage.getItem('petHavenLastBooking')||'null')}catch{}if(!b){el.innerHTML='<p>Your request has been saved.</p>';return}el.innerHTML=`<div class="detail-box"><h3>Booking request ${b.id}</h3><p><strong>${b.petName||'Your pet'}</strong> • ${b.service}</p><p>${b.date} at ${b.time} • ${b.area}</p><p>Pet Haven can confirm availability with you on ${PH.phoneDisplay}.</p></div>`}
function serviceName(id){return PH.services.find(s=>s.id===id)?.name||id}
function setupAdmin(){const table=document.getElementById('bookingRows');if(!table)return;const render=()=>{const rows=getBookings();document.querySelector('[data-stat="total"]')&&(document.querySelector('[data-stat="total"]').textContent=rows.length);document.querySelector('[data-stat="new"]')&&(document.querySelector('[data-stat="new"]').textContent=rows.filter(x=>x.status==='New').length);document.querySelector('[data-stat="confirmed"]')&&(document.querySelector('[data-stat="confirmed"]').textContent=rows.filter(x=>x.status==='Confirmed').length);document.querySelector('[data-stat="completed"]')&&(document.querySelector('[data-stat="completed"]').textContent=rows.filter(x=>x.status==='Completed').length);if(!rows.length){table.innerHTML='<tr><td colspan="8"><div class="empty">No bookings yet. Submit one from the public booking page to see it here.</div></td></tr>';return}table.innerHTML=rows.map(b=>`<tr><td><strong>${b.id}</strong><br><small>${new Date(b.createdAt).toLocaleString()}</small></td><td><strong>${b.customerName}</strong><br><small>${b.phone}</small></td><td><strong>${b.petName}</strong><br><small>${b.breed||b.petType}</small></td><td>${serviceName(b.service)}</td><td>${b.date}<br><small>${b.time}</small></td><td>${b.area}</td><td><span class="badge ${b.status.toLowerCase()}">${b.status}</span></td><td><select class="admin-btn" data-status="${b.id}"><option ${b.status==='New'?'selected':''}>New</option><option ${b.status==='Confirmed'?'selected':''}>Confirmed</option><option ${b.status==='Completed'?'selected':''}>Completed</option><option ${b.status==='Cancelled'?'selected':''}>Cancelled</option></select></td></tr>`).join('');document.querySelectorAll('[data-status]').forEach(sel=>sel.addEventListener('change',()=>{const data=getBookings();const row=data.find(x=>x.id===sel.dataset.status);if(row)row.status=sel.value;saveBookings(data);render()}))};render()}
function seedDemo(){const btn=document.getElementById('seedDemo');if(!btn)return;btn.addEventListener('click',()=>{if(getBookings().length&&!confirm('Add another sample booking?'))return;const d=new Date(Date.now()+2*86400000).toISOString().slice(0,10);const rows=getBookings();rows.unshift({id:uid(),createdAt:new Date().toISOString(),status:'New',customerName:'Demo Customer',phone:'0800 000 0000',email:'demo@example.com',petName:'Coco',petType:'Dog',breed:'Lhasa Apso',petSize:'Small',service:'full-groom',date:d,time:'11:00',area:'Lekki',address:'Demo address',notes:'Please keep the face fluffy.'});saveBookings(rows);location.reload()})}
document.addEventListener('DOMContentLoaded',()=>{setupNav();setupBooking();setupSuccess();setupAdmin();seedDemo()});
